### ISSUE TITLE
Quassel Crashes after connecting to core

### ISSUE THREAD

**Issue by Lugoues** [sandsmark/QuasselDroid#116]
The following exception is thrown when connecting to the quassel core. 

```
I/CoreConnService(13899): Connecting to core:[redacted] with username [redacted]
I/CoreConnection(13899): Connecting...
I/CoreConnection(13899): Sending client info...
I/CoreConnection(13899): Getting core info...
W/dalvikvm(13899): threadid=17: thread exiting with uncaught exception (group=0x41550700)
E/AndroidRuntime(13899): FATAL EXCEPTION: Thread-2994
E/AndroidRuntime(13899): java.lang.IllegalArgumentException: Illegal id 4271409
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.qtcomm.QMetaTypeRegistry.getTypeForId(QMetaTypeRegistry.java:174)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.qtcomm.QVariant$QVariantSerializer.unserialize(QVariant.java:119)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.qtcomm.QVariant$QVariantSerializer.unserialize(QVariant.java:67)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.qtcomm.QMetaTypeRegistry.unserialize(QMetaTypeRegistry.java:181)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.qtcomm.QMetaTypeRegistry.unserialize(QMetaTypeRegistry.java:184)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.io.CoreConnection.readQVariantMap(CoreConnection.java:659)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.io.CoreConnection.connect(CoreConnection.java:388)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.io.CoreConnection$ReadThread.doRun(CoreConnection.java:763)
E/AndroidRuntime(13899):        at com.iskrembilen.quasseldroid.io.CoreConnection$ReadThread.run(CoreConnection.java:721)
W/ActivityManager(  809):   Force finishing activity com.iskrembilen.quasseldroid.debug/com.iskrembilen.quasseldroid.gui.LoginActivity

```

**Comment by kenborge** [comment]
If you're not in the beta, could you try one of the newer version found here https://www.dropbox.com/sh/uxpckeobyz612qj/j2k7QsU7xC and see if the problem is still there. At the time i am writing this the newest version is 0.11.5

**Comment by justjanne** [comment]
@Lugoues can you test the latest versions?
